### PR TITLE
Link to a fork of this fork

### PR DESCRIPTION
**Pull request by spaze**
Link to @jakubjachym fork of this fork, would be better if he started co-maintaining this package but I guess it's too late now.

### CODE REVIEW

**Comment by JakubJachym** [comment]
I wanted to say it's never too late, but it looks like someone is already using my fork. So it perhaps it already too late.

**Comment by spaze** [comment]
No problem, happy you find it useful :-)

**Comment by spaze** [comment]
Btw, @JakubJachym I'd suggest following the original fork as there have been some PRs adjusting the rates that might be worth porting over to your fork to have the rates (more) correct, some from me, some from other contributors, e.g.
- https://github.com/driesvints/vat-calculator/pull/164
- https://github.com/driesvints/vat-calculator/issues/171
- etc.

**Comment by spaze** [comment]
@JakubJachym Checked the rates again and seems like your fork doesn't have
- all LU rates https://github.com/driesvints/vat-calculator/issues/166 + https://github.com/driesvints/vat-calculator/issues/167
- all CH rates https://github.com/driesvints/vat-calculator/pull/169
- zero VAT for Campione d'Italia, see the comment in https://github.com/driesvints/vat-calculator/pull/168#issuecomment-1874840188

Then you should have the same rates as the original version. I'd suggest watching all activity in the repo, it's really low volume, or at least issues + PRs. Guess that's all from me! 😅

**Pull request merged**
